# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to a recent 5.5.x version
  - 5.5

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit

notifications:
  slack: edwardsfam:PHGiYcg7b2Eq1dkABD3jDSSz

addons:
  code_climate:
    repo_token: f6227c9cb54fab59db37bd99a34ae7c3fc5eef4cb8a5dc313d73dfbab0319934

after_script:
  - vendor/bin/test-reporter
